apiVersion: apps/v1
kind: Deployment

metadata:
  name: my-deployment

spec:
  selector:
    matchLabels:
      app: bassant

  replicas: 3
  template:
    metadata:
      name: my-pod
      labels:
        app: bassant
    spec:
      containers:
        - image: saharfayez/ostask
          name: myimage
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "512Mi"
              cpu: "1"
            requests:
              memory: "100Mi"