apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    app: bassant
spec:
  containers:
    - image: saharfayez/ostask
      name: myimage
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80     
      resources:
        limits:
          memory: "512Mi"
          cpu: "1"
        requests:
          memory: "100Mi"